# Generated by Django 3.1.5 on 2021-01-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
